# Generated by Django 3.2.6 on 2021-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startup_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnd', models.IntegerField(max_length=10)),
                ('admin', models.IntegerField(max_length=10)),
                ('marketing', models.IntegerField(max_length=10)),
                ('state', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
    ]
