# Generated by Django 3.2.6 on 2021-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_titanic_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogcat_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
