# Generated by Django 3.2.6 on 2021-08-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0004_wine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic_info',
            name='embarc_s',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='acl',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='alcohol',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='ash',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='color_int',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='flavanoids',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='hue',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='malic_acid',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='mg',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='nonflavanoid_phenols',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='od',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='phenols',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='proanth',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='wine_info',
            name='proline',
            field=models.FloatField(blank=True, max_length=36, null=True),
        ),
    ]
